### ISSUE TITLE
Just a wild guess related to your last commit

### ISSUE THREAD

**Issue by nimble-123** [nicogeburek/2-minutes-of-sapui5-episode5#1]
Hi Nico,

it is just a wild guess, but in the past i had some trouble building mta's when using the dot notation in the build command section of the mta descriptor. Maybe this could be the reason the approuter won't work :)

https://github.com/nicogeburek/2-minutes-of-sapui5-episode5/blob/413f41c09dab5f22badf6eedda3cc0bd9f1147f0/episode5/mta.yaml#L20

**Comment by nicogeburek** [comment]
Wow I can't believe you actually took the time and looked at this 😍 
I did use this syntax in the past and it always worked, but I will play around with it.
Thanks a ton!

**Comment by nicogeburek** [comment]
Maybe I should clarify a little: Actually the approuter sort of works. I get to the index.html, but when I call the paths for the destination I get 404s...

**Comment by nimble-123** [comment]
Somewhere in the deeps of the SAP community it was mentioned that the order of defined routes actually is important. So maybe your /webapp route catches the requests and therefore the regex for other two routes did not get evaluated. But again a wild guess :) regex and me are no good friends 😉

**Comment by nicogeburek** [comment]
Yes I figured that out a while ago, too. Will see if this is the problem here. Thanks a lot!

**Comment by nicogeburek** [comment]
Oh wow, changing the order does make a difference. Now I get CORS errors on the routes... What? I thought the whole point of using the approuter was to avoid that :D I am pretty confident I have used the exact same structure before...

**Comment by nimble-123** [comment]
you could check the created destination service which is infused with your `Destination.json`. Maybe there is something not configured properly. But at least the request goes to the right URL and we're getting closer 😃

**Comment by nicogeburek** [comment]
Found out that it was the YouTube API not liking the approuter and forcing it to redirect the client to the actual URL, which lead to the CORS error. I'm not using the official [YouTube API](https://developers.google.com/youtube/v3/docs/playlistItems/list) instead of the RSS feed and that works 👌🏻
